### ISSUE TITLE
Possible wrong order of cleaning local directories

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#286] opened 2020-04-07 09:15 UTC
We use FTI as a plugin in PDI. One of our tests is not passing. The problem seems to be when we checkpoint with L1, ending the execution correctly with `keep_last_ckpt = 1`. This copies L1 checkpoint to L4. Size of node is set to 2 (full config: [fti_config_03.txt](https://github.com/leobago/fti/files/4443060/fti_config_03.txt) as txt, because github doesn't support .ini files). This means that 000004 and 000005 are in the same node and 000004 seems to delete the 000005 checkpoint file:
```
571: [FTI Debug - 000004] : Ckpt1-Rank4.fti 
571: [FTI Debug - 000004] : File ./fti_ckpt/node2/2020-04-07_10-31-41/l1/Ckpt1-Rank4.fti will be removed. 
571: [FTI Debug - 000004] : .. 
571: [FTI Debug - 000004] : Ckpt1-Rank5.fti 
571: [FTI Debug - 000004] : File ./fti_ckpt/node2/2020-04-07_10-31-41/l1/Ckpt1-Rank5.fti will be removed. 
```
And after that the 000005 tries to read the variable size in it:
```
571: [FTI Debug - 000005] : Variable with id is stored in 0 and information is stored in 0 
571: [FTI Debug - 000005] : Trying to load FTI checkpoint file (./fti_ckpt/node2/2020-04-07_10-31-41/l1/Ckpt1-Rank5.fti)... 
571: [ FTI Error - 000005 ] : Could not open FTI checkpoint file. : No such file or directory 
```
The full log: [log.txt](https://github.com/leobago/fti/files/4443104/log.txt)

Maybe I am doing something wrong, but for me it seems like the 000005 should take the size of variable from L4, because the 000004 after recovering from L4 is deleting all other levels checkpoints for the whole node.

The weird thing is that for other processes everything works fine, maybe other processes read the file before the main process in node deletes the files, but this repeats for every execution.

**Comment by leobago** [comment] 2020-04-07 09:24
Thank you @ksiero, we will take a look at it and come back to you.

**Comment by souchtal** [comment] 2020-05-04 15:58
Hello @ksiero, could you please attach the code that you are running including the part that makes calls to FTI's APIs (init, finalize, recover..)? I wasn't able to get the error you are reporting, the recovery goes as expected. It would be helpful if you retry the same execution scenario with FTI's latest version, there have been updates to the recovery function, and this might change the outcome you get.

**Comment by ksiero** [comment] 2020-07-22 11:56
I have tried the latest release, the problem remains. Maybe my API calls are wrong (didn't noticed before `FTI_RecoverVarInit` and `FTI_RecoverVarFinalize`. I didn't found any information about this API in Wiki.

I managed to crop the program as I could, where the problem remains.
Here is my test program (please remove the `.txt`, github needs it to be uploaded): 
[fti_test.c.txt](https://github.com/leobago/fti/files/4959756/fti_test.c.txt)

Here is my ini file:
[fti_config_03.ini.txt](https://github.com/leobago/fti/files/4959763/fti_config_03.ini.txt)

And here is the log with the errors:
Verbosity 2: 
[log.txt](https://github.com/leobago/fti/files/4959784/log.txt)
Verbosity 1:
[log_full.txt](https://github.com/leobago/fti/files/4959788/log_full.txt)

**Comment by souchtal** [comment] 2020-07-23 17:21
Indeed, some ranks were cleaning up ckpt files of other ranks before the latter would be able to read from them, hence causing a failure at the recovery. We made a fix to this and it will be soon merged to the master branch. We will also update the documentation to include the new APIs.
Thank you for pointing to the issue and for providing the input.

**Comment by leobago** [comment] 2020-07-24 09:44
Thank you for raising the issue @ksiero, the problem was that some processes arrived to FTI_Finalize before another process in the same node arrive to the FTI_RecoverVarInit, where they look for the files, which have been removed in the Finalize. Your code helped us reproduce and fix the issue. Please note that in a more realistic scenario, this will almost never happen because usually, you have a long simulation running between the FTI_RecoverVarInit and the FTI_Finalize, but because this was a small test with no real scientific simulation, this could happen. The issue has been fixed in the develop branch and we will merge it soon in the master branch.

**Comment by ksiero** [comment] 2020-07-24 12:30
The fix commit was merged to `develop` branch, not master. The `develop`  is 87 commits ahead, 16 commits behind master. Which one should I use?

**Closed** 2020-08-05 08:19 UTC
Labels: help wanted
